OnlineAuction/Controllers/AuctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using OnlineAuction.Models;
using Microsoft.AspNetCore.Authorization;
using System.Net.Http;
using Microsoft.AspNetCore.SignalR;
using Microsoft.AspNetCore.SignalR.Client;

namespace OnlineAuction.Controllers
{
    public class AuctionController : Controller
    {
        AuctionContext db;
        private readonly IEmailSender _emailSender;
        public AuctionController(AuctionContext context, IEmailSender emailSender)
        {
            db = context;
            _emailSender = emailSender;
        }
        public async Task<IActionResult> Index()
        {
            IQueryable <Bet> bets = db.Bets;
            if (db.Lots.Count() != 0 && db.Lots.FirstOrDefault().Status == true && db.Lots.FirstOrDefault().endDate < DateTimeOffset.UtcNow)
                return RedirectToAction("EndAuction");

            AuctionIndexViewModel viewModel = new AuctionIndexViewModel
            {
                Bets = await bets.AsNoTracking().ToListAsync(),
                ActualLot = db.Lots.FirstOrDefault()
            };
            //if (viewModel.ActualLot != null) viewModel.ActualLot.endDate = viewModel.ActualLot.endDate.ToLocalTime();

            return View(viewModel);
        }
        public async Task<IActionResult> Up()
        {
            if (db.Lots.Count() == 0 || db.Lots.FirstOrDefault().Status == false) return RedirectToAction("Index");
            if (db.Lots.FirstOrDefault().endDate < DateTimeOffset.UtcNow) return RedirectToAction("EndAuction");

            Bet newBet = new Bet();
            newBet.User = User.Identity.Name;

            if (db.Bets.Count() != 0) newBet.betSize = db.Bets.Max(p=>p.betSize) + db.Lots.FirstOrDefault().RateBet;
            else newBet.betSize = db.Lots.FirstOrDefault().StartBet;

            db.Lots.FirstOrDefault().ActualCost = newBet.betSize;
            db.Lots.FirstOrDefault().Owner = User.Identity.Name;
            db.Bets.Add(newBet);

            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Lot lot, int Time)
        {
            if (db.Lots.Count() != 0 && db.Lots.FirstOrDefault().Status == true)
            {
                if (db.Bets.Count() != 0) SendMsg();
            }
            foreach (var element in db.Bets) db.Bets.Remove(element);
            foreach (var element in db.Lots) db.Lots.Remove(element);
            lot.Status = true;
            lot.endDate = DateTimeOffset.UtcNow;
            lot.endDate = lot.endDate.AddMinutes(Time);
            db.Lots.Add(lot);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> EndAuction()
        {
            if (db.Lots.Count() == 0 || db.Lots.FirstOrDefault().Status == false) return RedirectToAction("Index");
            db.Lots.FirstOrDefault().Status = false;
            if (db.Bets.Count() != 0) SendMsg();
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private async void SendMsg()
        {
            string msg = "Товар \"" + db.Lots.FirstOrDefault().Name + "\" успешно куплен на аукционе за " + db.Lots.FirstOrDefault().ActualCost;
            await _emailSender.SendEmailAsync(db.Keys.FirstOrDefault().Value, new List<string> { db.Lots.FirstOrDefault().Owner }, "Аукцион", msg);
        }
    }
}

OnlineAuction/Views/Auction/Create.cshtml
@model OnlineAuction.Models.Lot
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    ViewBag.Title = "Добавление лота";
}
<form asp-action="create" asp-controller="auction">
    <div class="form-group">
        <label asp-for="Name" class="control-label">@Localizer["Name"]</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="StartBet" class="control-label">@Localizer["Cost"]</label>
        <input type="number" asp-for="StartBet" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Company" class="control-label">@Localizer["Company"]</label>
        <input type="text" asp-for="Company" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="RateBet" class="control-label">@Localizer["RateBet"]</label>
        <input type="number" asp-for="RateBet" class="form-control" />
    </div>
    <div class="form-group">
        <input type="number" name="Time" />
        <input type="submit" value="@Localizer["Send"]" class="btn btn-default" />
    </div>
</form>

OnlineAuction/Views/Auction/Index.cshtml
@using OnlineAuction.Models
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model AuctionIndexViewModel
<!--импортируем tag-хелперы проекта-->
@addTagHelper *, OnlineAuction

@{
    ViewData["Title"] = "Auction Page";
}
@if (User.IsInRole("admin") == true)
{
    <a asp-controller="Auction" asp-action="Create">@Localizer["AddLot"]</a>
    <a asp-controller="Auction" asp-action="EndAuction">@Localizer["EndAuc"]</a>
}
@{
    var str = Model.ActualLot.endDate.ToString("o");
}
<input type="text" id="dateIn" value="@str" hidden=""/>
<div>
    <dl class="dl-horizontal">
        <dt>@Localizer["Name"]</dt>
        <dd>
            @Html.DisplayFor(model => model.ActualLot.Name)
        </dd>
        <dt>@Localizer["ActualCost"]</dt>
        <dd>
            @Html.DisplayFor(model => model.ActualLot.ActualCost)
        </dd>
        <dt>@Localizer["StartCost"]</dt>
        <dd>
            @Html.DisplayFor(model => model.ActualLot.StartBet)
        </dd>
        <dt>@Localizer["RateBet"]</dt>
        <dd>
            @Html.DisplayFor(model => model.ActualLot.RateBet)
        </dd>
        <dt>@Localizer["Company"]</dt>
        <dd>
            @Html.DisplayFor(model => model.ActualLot.Company)
        </dd>
        <dt>@Localizer["Status"]</dt>
        <dd>
            @Html.DisplayFor(model => model.ActualLot.Status)
        </dd>
        <dt>@Localizer["EndDate"]</dt>
        <dd>
           <input type="text" id="dateOut"/>
        </dd>
    </dl>
</div>

<form asp-controller="Auction" asp-action="Up">
    <p>
        <input type="submit" value="@Localizer["Up"]" />
    </p>
</form>

<table class="table">
    @foreach (Bet bet in Model.Bets)
    {
        <tr>
            <td>@bet.User</td>
            <td>@bet.betSize</td>
        </tr>
    }
</table>
<script>
    let utcDate = document.getElementById("dateIn").value;
    let localDate = new Date(utcDate);
    document.getElementById("dateOut").value = localDate;
</script>